### ISSUE TITLE
Doesnt startet - just "Loading"

### ISSUE THREAD

**Issue by fischbear** [relm923/MMM-Roomba#16]
I installed the module and Dorita. With Dorit I got the BLID and the password. All I see on the mirror is "Loading". For Username, in the config file, I tried BLID and my registration email. both without success. Where could the mistake lie?

**Comment by fischbear** [comment]
I test with the rest api and get thhis failure:

RequestError: Error: connect ECONNREFUSED 192.168.2.52:443
    at new RequestError (/home/pi/rest980/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/home/pi/rest980/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/home/pi/rest980/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/home/pi/rest980/node_modules/request/request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.onRequestError (/home/pi/rest980/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:494:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by fischbear** [comment]
ok! i Get it! Can i put 2 robots in the script?
