### ISSUE TITLE
Error Connecting to Roomba 960

### ISSUE THREAD

**Issue by dfuselli** [relm923/MMM-Roomba#6]
[2020-06-06 23:37:18.723] [LOG]    Whoops! There was an uncaught exception...
[2020-06-06 23:37:18.723] [ERROR]  Error: error:100000b1:SSL routines:OPENSSL_internal:NO_CIPHER_MATCH
    at Object.createSecureContext (_tls_common.js:177:13)
    at Object.connect (_tls_wrap.js:1401:48)
    at Object.buildBuilder (/opt/magic_mirror/modules/MMM-Roomba/node_modules/mqtt/lib/connect/tls.js:13:20)
    at MqttClient.wrapper [as streamBuilder] (/opt/magic_mirror/modules/MMM-Roomba/node_modules/mqtt/lib/connect/index.js:140:36)
    at MqttClient._setupStream (/opt/magic_mirror/modules/MMM-Roomba/node_modules/mqtt/lib/client.js:277:22)
    at new MqttClient (/opt/magic_mirror/modules/MMM-Roomba/node_modules/mqtt/lib/client.js:258:8)
    at Object.connect (/opt/magic_mirror/modules/MMM-Roomba/node_modules/mqtt/lib/connect/index.js:143:10)
    at localV2 (/opt/magic_mirror/modules/MMM-Roomba/node_modules/dorita980/lib/v2/local.js:30:23)
    at new local (/opt/magic_mirror/modules/MMM-Roomba/node_modules/dorita980/index.js:17:10)
    at Class.updateStats (/opt/magic_mirror/modules/MMM-Roomba/node_helper.js:53:16)
    at Class.scheduleUpdates (/opt/magic_mirror/modules/MMM-Roomba/node_helper.js:95:8)
    at Class.handleStartNotification (/opt/magic_mirror/modules/MMM-Roomba/node_helper.js:45:8)
    at Class.socketNotificationReceived (/opt/magic_mirror/modules/MMM-Roomba/node_helper.js:28:10)
    at Socket.<anonymous> (/opt/magic_mirror/js/node_helper.js:113:11)
    at Socket.emit (events.js:200:13)
    at /opt/magic_mirror/node_modules/socket.io/lib/socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:82:9) {
  library: 'SSL routines',
  function: 'OPENSSL_internal',
  reason: 'NO_CIPHER_MATCH',
  code: 'ERR_SSL_NO_CIPHER_MATCH'
}

**Comment by dfuselli** [comment]
Here the details
https://github.com/electron/electron/issues/20759

**Comment by dfuselli** [comment]
Solution is here
https://github.com/koalazak/dorita980/issues/102

update to last dorita980 version 3.1.7 and update cipher version through env property. It happens only for roomba 960 version, not for 980

**Comment by relm923** [comment]
Thanks for tracking down the issue @dfuselli. I've upgraded all dependencies and added a note in the README
